FROM postgres:11.1-alpine
LABEL maintainer="mouradhsam@gmail.com"

# Install needed packages
RUN apk update && apk upgrade && \
    apk add --no-cache \
        python3 \
        python3-dev \
        curl \
        gcc \
        musl-dev \
        apline-sdk

# Symlink python
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip

# Move scripts and config files
ADD . /code

# Set working directory in image
WORKDIR /code

# Environment variables
ENV DBHOST chibiz_db_1 \
    DBPORT 5432 \
    DBNAME chibizlic \
    APP_TOKEN lek1JOcM5NsT29aL97QKF3EvK \
    DATA_DOMAIN data.cityofchicago.org \
    DATA_ID xqx5-8hwx \
    INITIAL_DATA_LIMIT 2000000 \
    INITIAL_DATA_FILE business_licenses.json

# Run database setup script
